// markdownReport — turn the /api/v1/scan/audit JSON response into a
// structured Markdown file that a developer can read in their editor,
// commit to a repo, or share in a PR review.

export interface AuditApiResponse {
  scanId: string;
  timestamp: number;
  user: { username: string | null; email: string | null };
  project: {
    framework: string;
    version: string;
    totalFiles: number;
    avgLines: number;
  };
  score: {
    health: number;
    grade: string;
    /** @deprecated kept for API backward compat; not rendered. */
    risk?: string;
    modularity: number;
    avgCoupling: number;
    avgComplexity: number;
    criticalFiles: number;
    circularDeps: number;
  };
  benchmark: Array<{
    metric: string;
    value: number;
    p50: number;
    p90: number;
    percentile: number;
    interpretation: 'higher-better' | 'lower-better';
    label: 'bootstrap' | 'community';
  }>;
  trend: {
    hasHistory: boolean;
    pointCount: number;
    points: Array<{ date: string; score: number; avgCoupling: number; avgComplexity: number }>;
    scoreDelta: number;
    couplingDelta: number;
    complexityDelta: number;
    direction: 'improving' | 'stable' | 'declining';
    projection: {
      daysToCBoundary: number | null;
      daysToDBoundary: number | null;
      r2: number | null;
    };
  };
  fanInOut: {
    hubs: Array<{ file: string; fanIn: number; fanOut: number }>;
    orphans: string[];
  };
  rankedCycles: Array<{ cycle: string[]; length: number; sharedModules: string[]; impact: number }>;
  hotspotClusters: {
    folderClusters: Array<{ folder: string; count: number; pct: number }>;
    namePatterns: Array<{ pattern: string; examples: string[] }>;
  };
  correlations: Array<{
    file: string;
    reasons: string[];
    severity: 'warning' | 'critical';
    reasonCount: number;
  }>;
  frameworkSmells: string[];
  barrels: Array<{ file: string; reExportCount: number }>;
  godComponents: Array<{
    file: string;
    lines: number;
    imports: number;
    hooks: number;
    jsxReturns: number;
    reasons: string[];
  }>;
  depFindings: Array<{
    name: string;
    userVersion: string;
    currentMajor: number;
    bundleImpact: string;
    severity: string;
    message: string;
  }>;
  insights: string[];
}

export function generateMarkdownReport(
  audit: AuditApiResponse,
  projectName: string
): string {
  const lines: string[] = [];
  const date = new Date(audit.timestamp).toISOString().slice(0, 10);

  // ===== HEADER =====
  lines.push(`# Architectural Audit — ${projectName}`);
  lines.push('');
  lines.push(`> Generated by [archradar](https://fewcompany.com) on ${date}`);
  lines.push(`> Signed in as \`@${audit.user.username ?? 'unknown'}\``);
  lines.push(`> Scan ID: \`${audit.scanId}\``);
  lines.push('');
  lines.push('---');
  lines.push('');

  // ===== EXECUTIVE SUMMARY =====
  lines.push('## Executive Summary');
  lines.push('');
  lines.push(`- **Framework:** ${audit.project.framework} ${audit.project.version}`);
  lines.push(`- **Files scanned:** ${audit.project.totalFiles}`);
  lines.push(
    `- **Health score:** **${audit.score.health}/100** (grade ${audit.score.grade})`
  );
  lines.push(
    `- **Avg file size:** ${audit.project.avgLines} lines · **Avg coupling:** ${audit.score.avgCoupling} imports · **Avg complexity:** ${audit.score.avgComplexity}`
  );
  lines.push(`- **Modularity score:** ${audit.score.modularity}/100`);
  lines.push('');

  if (audit.insights.length > 0) {
    lines.push('**Key findings:**');
    lines.push('');
    for (const insight of audit.insights) {
      lines.push(`- ${insight}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');

  // ===== HISTORICAL TRENDS =====
  lines.push('## Historical Trends');
  lines.push('');
  if (!audit.trend.hasHistory || audit.trend.pointCount < 2) {
    lines.push(
      `> _This is your ${audit.trend.pointCount === 0 ? 'first' : 'first'} scan for this project. Historical trends will appear after the second audit._`
    );
    lines.push('');
  } else {
    const t = audit.trend;
    const arrow = t.direction === 'improving' ? '↗' : t.direction === 'declining' ? '↘' : '→';
    lines.push(`- **Direction:** ${arrow} ${t.direction} (${t.pointCount} scans in history)`);
    lines.push(
      `- **Score delta:** ${t.scoreDelta >= 0 ? '+' : ''}${t.scoreDelta} (first scan ${t.points[0].score} → latest ${t.points[t.points.length - 1].score})`
    );
    lines.push(
      `- **Coupling delta:** ${t.couplingDelta >= 0 ? '+' : ''}${t.couplingDelta.toFixed(1)}`
    );
    lines.push(
      `- **Complexity delta:** ${t.complexityDelta >= 0 ? '+' : ''}${t.complexityDelta.toFixed(1)}`
    );

    // Projections are only shown when R² ≥ 0.5 (decent linear fit).
    // When R² is high we still annotate it so the reader can judge confidence.
    if (t.projection.daysToCBoundary !== null) {
      const fitNote = t.projection.r2 !== null ? ` _(R²=${t.projection.r2.toFixed(2)})_` : '';
      lines.push(
        `- ⚠️ **Projection:** At current trajectory, this project crosses into grade C in ~${t.projection.daysToCBoundary} days.${fitNote}`
      );
    }
    if (t.projection.daysToDBoundary !== null) {
      const fitNote = t.projection.r2 !== null ? ` _(R²=${t.projection.r2.toFixed(2)})_` : '';
      lines.push(
        `- 🔴 **Projection:** At current trajectory, this project crosses into grade D in ~${t.projection.daysToDBoundary} days.${fitNote}`
      );
    }
    lines.push('');

    lines.push('<details><summary>Full history</summary>');
    lines.push('');
    lines.push('| Date | Score | Coupling | Complexity |');
    lines.push('|------|-------|----------|------------|');
    for (const p of t.points) {
      lines.push(
        `| ${p.date.slice(0, 10)} | ${p.score} | ${p.avgCoupling.toFixed(1)} | ${p.avgComplexity.toFixed(1)} |`
      );
    }
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  lines.push('---');
  lines.push('');

  // ===== BENCHMARK =====
  // All four metrics should share the same label (community or bootstrap).
  const baselineLabel = audit.benchmark[0]?.label ?? 'bootstrap';
  const isCommunity = baselineLabel === 'community';

  lines.push(
    isCommunity
      ? '## Benchmark vs Community Baseline'
      : '## Benchmark vs Bootstrap Baseline'
  );
  lines.push('');
  lines.push(`Comparison against **${audit.project.framework}** baseline.`);
  lines.push('');
  if (isCommunity) {
    lines.push(
      '> _Community baseline — derived from scans of real open source projects. Updated periodically as we grow the sample._'
    );
  } else {
    lines.push(
      '> ⚠️ _Bootstrap baseline — heuristic estimates while we accumulate real samples. Use as a rough signal, not a score._'
    );
  }
  lines.push('');
  lines.push('| Metric | Your value | p50 | p90 | Percentile | Status |');
  lines.push('|--------|-----------|-----|-----|------------|--------|');
  for (const b of audit.benchmark) {
    // percentile always means "your position in the distribution".
    // For higher-better: high percentile = good. For lower-better: high percentile = bad.
    const isGood =
      b.interpretation === 'higher-better' ? b.percentile >= 50 : b.percentile <= 50;
    const status = isGood ? '✓ better than p50' : '⚠ above p50';
    lines.push(
      `| ${b.metric} | ${b.value} | ${b.p50} | ${b.p90} | ${b.percentile}% | ${status} |`
    );
  }
  lines.push('');
  lines.push('---');
  lines.push('');

  // ===== ARCHITECTURAL DEBT =====
  lines.push('## Architectural Debt');
  lines.push('');

  // Correlations
  if (audit.correlations.length > 0) {
    lines.push('### 🎯 Cross-correlated bottlenecks');
    lines.push('');
    lines.push(
      'Files that appear in **multiple** risk lists (complexity, coupling, size). Fixing these produces the most value.'
    );
    lines.push('');
    for (const c of audit.correlations) {
      const icon = c.severity === 'critical' ? '🔴' : '⚠️';
      lines.push(
        `- ${icon} **\`${c.file}\`** — ${c.reasons.join(', ')} _(${c.reasonCount} risk lists)_`
      );
    }
    lines.push('');
  }

  // Fan-in/fan-out
  if (audit.fanInOut.hubs.length > 0) {
    lines.push('### 🎯 Central hubs (fan-in)');
    lines.push('');
    lines.push('Files with many incoming imports. Changes cascade through the codebase.');
    lines.push('');
    for (const h of audit.fanInOut.hubs) {
      if (h.fanIn === 0) continue;
      lines.push(`- \`${h.file}\` — **fan-in ${h.fanIn}**, fan-out ${h.fanOut}`);
    }
    lines.push('');
  }

  if (audit.fanInOut.orphans.length > 0 && audit.fanInOut.orphans.length <= 10) {
    lines.push('### 🎯 Orphan modules (dead code candidates)');
    lines.push('');
    lines.push('Files with zero incoming imports — likely unused.');
    lines.push('');
    for (const o of audit.fanInOut.orphans) {
      lines.push(`- \`${o}\``);
    }
    lines.push('');
  }

  // Hotspot clustering
  if (audit.hotspotClusters.folderClusters.length > 0) {
    lines.push('### 🎯 Complexity clustering');
    lines.push('');
    for (const c of audit.hotspotClusters.folderClusters) {
      lines.push(`- \`${c.folder}/\` — ${c.count} hotspots (${c.pct}% of total)`);
    }
    lines.push('');
  }

  // Cycles
  if (audit.rankedCycles.length > 0) {
    lines.push('### 🎯 Circular dependencies');
    lines.push('');
    for (const c of audit.rankedCycles.slice(0, 3)) {
      lines.push(
        `- **${c.length} files** · impact ${c.impact.toFixed(1)}${c.sharedModules.length > 0 ? ` · shared modules: ${c.sharedModules.map((s) => `\`${s}\``).join(', ')}` : ''}`
      );
      lines.push(`  ${c.cycle.map((f) => `\`${f}\``).join(' → ')}`);
    }
    lines.push('');
  }

  // God components
  if (audit.godComponents.length > 0) {
    lines.push('### 🎯 God components');
    lines.push('');
    lines.push('Components accumulating too many responsibilities.');
    lines.push('');
    for (const g of audit.godComponents.slice(0, 5)) {
      lines.push(
        `- **\`${g.file}\`** — ${g.reasons.join(', ')}`
      );
    }
    lines.push('');
  }

  // Barrel files
  if (audit.barrels.length > 0) {
    lines.push('### 🎯 Barrel files (tree-shaking hazards)');
    lines.push('');
    for (const b of audit.barrels.slice(0, 5)) {
      lines.push(`- **\`${b.file}\`** re-exports ${b.reExportCount} modules`);
    }
    lines.push(
      '> Barrel files defeat tree-shaking: importing one symbol pulls the whole barrel into the graph.'
    );
    lines.push('');
  }

  // Framework smells
  if (audit.frameworkSmells.length > 0) {
    lines.push('### 🎯 Framework-specific smells');
    lines.push('');
    for (const s of audit.frameworkSmells) {
      lines.push(`- ${s}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');

  // ===== DEPENDENCY REPORT =====
  lines.push('## Dependency Report');
  lines.push('');
  if (audit.depFindings.length === 0) {
    lines.push('No major dependency issues found in the static intelligence table.');
    lines.push('');
  } else {
    const critical = audit.depFindings.filter((d) => d.severity === 'critical');
    const warning = audit.depFindings.filter((d) => d.severity === 'warning');

    if (critical.length > 0) {
      lines.push('### 🔴 Critical');
      lines.push('');
      for (const d of critical) {
        lines.push(`- **\`${d.name}@${d.userVersion}\`** — ${d.message}`);
      }
      lines.push('');
    }
    if (warning.length > 0) {
      lines.push('### ⚠️ Warnings');
      lines.push('');
      for (const d of warning) {
        lines.push(`- \`${d.name}@${d.userVersion}\` — ${d.message}`);
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');

  // ===== FOOTER =====
  lines.push('## About this report');
  lines.push('');
  lines.push('This audit was generated by [archradar](https://fewcompany.com), an Architectural Intelligence Engine for modern frontend teams.');
  lines.push('');
  lines.push(
    '**Premium features used:** historical trend projection, dependency intelligence, fan-in/fan-out analysis, framework baselines, cross-correlation, pattern detection (barrels, god components).'
  );
  lines.push('');
  lines.push('> Free during early access — paid after Few Company incorporation.');
  lines.push('');

  return lines.join('\n');
}
